os:
  - linux
  - osx
language: python
python:
  - "2.7"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
script:
  - python -m unittest discover -s tests
